### ISSUE TITLE
(show-startup-message) stucks cursor on top in small console window

### ISSUE THREAD

**Issue by jorge-leon** [hughbarney/femto#15]
If the console windows has less lines then inserted by `(show-startup-message)` the cursor gets stuck on top of the window and cannot be moved with the cursor+down, or cursow+right keys.  It moves though with cursor up, left, or page up/down.

Can be fixed by adding `(end-of-buffer)` after inserting the last string.

**Comment by hughbarney** [comment]
Your fix sounds right.  Can you do a PR.

**Comment by jorge-leon** [comment]
Yes I'll be happy to followup on all issues raised by me.

I'd appreciate you consider to look into the "make-distfriendly" PR #12 first, as this will facilitate work for me, beeing a very git-unsavvy person.

**Comment by hughbarney** [comment]
P#12 - Yes - I will have a go.   It is a while since I have integrated a PR to be honest to need to check on the mechanics.
I might try this afternoon, bear with me, as its been a while.

**Comment by hughbarney** [comment]
This is fixed by my most recent push.
The fix is to ensure the loacl config is loaded afther the systen configuration
