### ISSUE TITLE
Feature: Load all files listed on commandline

### ISSUE THREAD

**Issue by jorge-leon** [hughbarney/femto#6]
_femto_ is only processing the first command line argument.  Therefore only one file can be loaded on startup.

Instead all arguments on the command line should be processed and existing files loaded into new buffers.

Note: I might well implement this feature and prepare a pull request as soon as I get around it.

**Comment by hughbarney** [comment]
Pull request for this would be welcome.

The command line arg code should problem we done in a seperate C file so that main is kept simple and not bloated.

**Comment by hughbarney** [comment]
Fixed in v2.12 thansk for jorge-leon
