### ISSUE TITLE
Feature: Allow to specify a target to jump to on the command line

### ISSUE THREAD

**Issue by jorge-leon** [hughbarney/femto#7]
A convention for *nix text editors is, that a command line argument starting with `+` specifies a target inside the loaded file, where the cursor/insert point is set to.

The simplest target is `+`_n_, where _n_ is a line number. A negative _n_ counts from the end of file.

Variations are:

- `+`_n_`,`_c_: where _c_ is a column number. A negative _c_ counts from the end of line.
- `+/`_pat_: where _pat_ is a search pattern. The point is set to the first match from the start of the file.
- `+?`_pat_: ditto, butt search from the end of the file.
- `+`_command_: execute _command_ after loading the file.

I propose to allow for parsing the commandline as follows: [[`+`_arg_ ..] _file_] ..], i.e.:
Any number of `+` arguments can be given, the last before a _file_ argument applies to that file.

Note: I might well implement this feature and prepare a pull request as soon as I get around it.

**Comment by hughbarney** [comment]
Yes - nice idea. One day I will find time to implement that.

**Comment by hughbarney** [comment]
$ femto README.md +5
did not go to line 5

$ femto README.md + 5
Segmentation fault (core dumped)

with a space after the + got a core dump.

**Comment by hughbarney** [comment]
$ femto +5 README.md
$ femto +50 README.md

These work.

**Comment by jorge-leon** [comment]
> $ femto README.md +5 did not go to line 5
> 
> $ femto README.md + 5 Segmentation fault (core dumped)
> 
> with a space after the + got a core dump.

The core dump is a bug in the `getopts` defun (or in the tiny-lisp interpreter if you like). I'll figure out a fix.
