### ISSUE TITLE
Feature: read global femto.rc if none is found in home directory

### ISSUE THREAD

**Issue by jorge-leon** [hughbarney/femto#8]
In order to be able to use _femto_ without user specific setup a fallback femto.rc should be provided.
I propose to read `/etc/femto.rc` if `$HOME/femto.rc` is not found (or fails to load).

Additionally I propose to rename the personal `femto.rc` to `.femtorc`, at least on *nix systems in order to make it a hidden file and align better with common practice.

Note: I might well implement this feature and prepare a pull request as soon as I get around it.

**Comment by hughbarney** [comment]
pull request for this would be welcome.

**Comment by hughbarney** [comment]
I think the solution will work as follows.

1) attempt to load femto.rc
2) if that fails look for /use/local/bin/femto.rc
3) if that fails carry on with no config loaded

I will probably continue to use femto.rc as it will work better on Windows and MacOS etc.

**Comment by sleep-walker** [comment]
If you want to be a bit distro friendly, consider using I think that `/usr/lib/femto.rc` or `/usr/lib/femto/femto.rc` instead. Also, user typically has own config in ~/.config so ~/.config/femto/femto.rc would be more suitable than ~/femto.rc. OTOH, this should be easy to patch while packaging...

**Comment by jorge-leon** [comment]
Femto Lisp can `load` another file.  A sound approach could be to distribute a global femto.rc which figures out by itself where to load global and user specific initialization.  Thus there is less to hardcode in femto itself.

Distro friendliness:

- `make install` should
   - copy the femto binary to `"$DESTDIR/$BINDIR"`, where `BINDIR` should be set at compile time, by default to '/usr/local/bin'.
   - copy `femto.rc` to "$DESTDIR/$DATADIR/femto/", where `DATADIR` should be set a compile time by default to `/usr/local/share`

DESTDIR should not be set at all: it allows the distro maintainer to locally "install" into a work directory which can than be packaged and distributed.

Defaults are given for Linux/*nix systems, On Windows both might be set to the empty string and DESTDIR set to `%PROGRAMFILES%\Femto` or so.

See also https://www.gnu.org/prep/standards/html_node/Directory-Variables.html.

**Comment by hughbarney** [comment]
Happy to take a PR for the makefile change you are proposing.

**Comment by jorge-leon** [comment]
This issue is closed with PR #12, though in a different way: the PR loads a global `femto.rc`, from `main.c`. Anything else is handled in Lisp from within `femto.rc` itself.

**Comment by hughbarney** [comment]
#PR12 is now  merged in.
