### ISSUE TITLE
Feature: skip -- arguments on commandline

### ISSUE THREAD

**Issue by jorge-leon** [hughbarney/femto#9]
When using _femto_ as default text editor on Debian (and probably others) it can be called with `--` before filename arguments (e.g. by `visudo`).  `--` meaning: "do not treat remaining arguments with leading `-` as options".

_femto_ should skip the first `--` encountered on the command line so it can be used in these situations.

Note: I might well implement this feature and prepare a pull request as soon as I get around it.

**Comment by hughbarney** [comment]
Pull request welcome.

**Comment by hughbarney** [comment]
Not quite sure how to test.

$ femto --- README.md 

Need a test case that shows it working

**Comment by jorge-leon** [comment]
As of now there are no command line options (starting with `-`). The builtin Lisp `getopts` defun will happily open and create files starting with `-`. Therefore there is no need for a `--` guard at this moment
